server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    cluster:
      nodes: 172.10.0.91:6379,172.10.0.92:6379,172.10.0.93:6379,172.10.0.94:6379,172.10.0.95:6379,172.10.0.96:6379



mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.wenjifeng.idgenerator.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:com/wenjifeng/idGenerator/mapper/*.xml                       # mapper映射文件